### ISSUE TITLE
Possible IndexOutOfBoundsException in StateRepresentation.tryFindLocalHandler

### ISSUE THREAD

**Issue by simonreye** [oxo42/stateless4j#21]
In my case when a guard condition is false the 'actual' array designed to have the one and only TriggerBehaviour is empty.

Perhaps this needs to be added to the code:

if (actual.isEmpty())
{
    return null;
}

**Comment by Ktar5** [comment]
Apparently already fixed in the return statement of tryFindLocalHandler
`return actual.isEmpty() ? null : actual.get(0);`
