### ISSUE TITLE
Please use slf4j instead of java.util.logging

### ISSUE THREAD

**Issue by benzht** [oxo42/stateless4j#25]
JUL is but one of many widely used logging framework. Having many of these in the same application is really not nice.
slf4j provides a logging API for libraries with several backends, like JUL, log4j, apache, logback etc. and thus allows the users of the library to seamlessly integrate the logging of the library with the rest of their application.

**Comment by literadix** [comment]
I see that slf4j is used, but I have to exclude it when I have already a slf4j instance in my project. This is done by:

        <dependency>
            <groupId>com.github.oxo42</groupId>
            <artifactId>stateless4j</artifactId>
            <version>2.5.0</version>
            <exclusions>
              <exclusion>
                <artifactId>slf4j-jdk14</artifactId>
                <groupId>org.slf4j</groupId>
              </exclusion>
            </exclusions>
        </dependency>

Probably you could not export slf4j at all or simply use java logging which can be also logged by slf4j.I personally prefer libraries with nearly no dependencies outside JVM.

**Comment by benzht** [comment]
@literadix,
I think you uncovered a problem in the POM of stateless4j (pulled from my branch) - instead of depending on slf4j-jdk14, which is an actual binding/implementation of the API, it should rather depend on slf4j-api and that should not create any conflicts in your application.
A dependency to slf4j-jdk14 may be required for the 'testing' scope in stateless4j. I will look into that - probably during the weekend.

**Comment by literadix** [comment]
Probably it could be ok to remove all logging at all from the core library and only inject logging for transitions as an abstract interface (onFile() ... onError()). Both default implementations would be empty ... if yomeone (even testers) need logging, they could override both messages.

By the way: could you please provide an example how to implement external state storage? I tried to figure out how to use the function for this ... but with no success. 

Thank you very much in advice.

**Comment by benzht** [comment]
@literadix I have just pushed the fix to the dependencies to my fork and it became also part of this pull request (not merged, yet). Personally , I prefer using a widely-used logging framework with lots of design experience and development resources behind it to a self-made solution.
Regarding the external state storage I fear I cannot help you further - I have not used this feature, yet.
Success!

**Comment by Ktar5** [comment]
Fixed
