### ISSUE TITLE
StateMachine.publicFire() logs at INFO level

### ISSUE THREAD

**Issue by blue666man** [oxo42/stateless4j#40]
For FSMs with a large number of triggers, this fills logs with a lot of noise.  Proposing to default to DEBUG with a constructor overload.

**Comment by fabienrenaud** [comment]
Logging is done with sl4fj so you can tune your log4j(2) or logback configuration to not show info logs of stateless4j if they are too noisy...
Unless there are other info logs you want to keep?

**Comment by leachbj** [comment]
As noted in the mqlight/java-mqlight reference, we're seeing these log entries generated from the state machine but have no desire to see the logged at INFO level since they are essentially meaningless to our application where the state machine is hidden behind a higher level API.

**Comment by erakadjiev** [comment]
As others above say, these log entries are annoying at INFO level.
In my opinion, the best would be if that log call was removed altogether.
Since that's the only place where logging is done in Stateless4j, the slf4j dependency could be removed too.

**Comment by Ktar5** [comment]
Can we at least get an option to toggle logging per state machine or something?
