### ISSUE TITLE
State transitions when onEntry throws an Exception

### ISSUE THREAD

**Issue by cycle222** [oxo42/stateless4j#44]
If a runtime exception is thrown during onEntry (StateMachineConfig) Action, the state machine still transitions to the target state. In my particular use case, the onEntry actions and the state transition are intrinsically tied and therefore must either both be executed or no transition should occur at all.

Example:

```java
phoneCallConfig.configure(State.Ringing)
        .onEntry(new Action() {
            @Override
            public void doIt() {
                throw new RuntimeException("Deliberately thrown");
            }
        });
```

In the above snippet, the onEntry action always fails but the state always transitions to Ringing. For what I'm doing at the moment, onEntry must complete for the state to transition.

* Option A: onEntry should never affect the state transition. Users will have to write their own fork of stateless4j to handle this case
* Option B: onEntry should complete, otherwise 'roll back' the transition
* Option C: Expose a facility in the framework to allow atomic transition and onEntry actions

Any preferences/advice from the stateless4j community on how to implement my requirement?

Thanks
Jonathan

**Comment by tuncatunc** [comment]
If you need to conditionally leave the state, try to use permitIf while configuring state.
