### ISSUE TITLE
Not found the stateless jar(2.5.2-SNAPSHOT) in maven repo.

### ISSUE THREAD

**Issue by prabhabisht** [oxo42/stateless4j#56]
Hi Team , I tried  to download stateless4j with maven dependency 
`<dependency>
    <groupId>com.github.oxo42</groupId>
    <artifactId>stateless4j</artifactId>
    <version>2.5.2-SNAPSHOT</version>
    </dependency>`
 
but as I saw in [maven repo ](http://mvnrepository.com/artifact/com.github.oxo42/stateless4j) this version is not found . Can anyone help me to find the appropriate repo for this version.

**Comment by Ktar5** [comment]
2.5.2 was never released on the maven apparently. The maven build is going to be changed soon. So keep a look out.
