### ISSUE TITLE
permitIf being called multiple times per transition

### ISSUE THREAD

**Issue by breevo** [oxo42/stateless4j#58]
More of a question than an issue, but I'm evaluating stateless4j and noticed that my guard is being called twice each time a transition occurs. Is this expected?

Configuration for the state in question looks like this:

```java
stateConfig.configure(UnitState.offline)
    .onEntry(t -> updateListenersOnEntry(t))
    .onEntry((t) -> log(t))
    .onExit(t -> updateListenersOnExit(t))
    .permitIf(UnitStateTrigger.updating, UnitState.updated, () -> {
        return applyGuards(getState(), UnitStateTrigger.updating, UnitState.updated);
    })
    .permit(UnitStateTrigger.registrationFailure, UnitState.initialized)
    .permit(UnitStateTrigger.receivingInitialState, UnitState.updated)
    .permit(UnitStateTrigger.enabling, UnitState.online);
```

**Comment by Ktar5** [comment]
I wrote some crude tests and couldn't reproduce. Can you confirm if this bug is still a problem?

**Comment by Ktar5** [comment]
Thank you for pointing this out! It seems to be an overlooked side effect of getPermittedTriggers. Will research a fix.
