### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by ezaquarii** [oxo42/stateless4j#70]
Is this project still being maintained? Latest release is 2.5.0. Some fixes are not released.

**Comment by oxo42** [comment]
The short answer is no.  If anyone wants to take ownership of this repo, I am happy to transfer it.  I no longer work with Java

**Comment by ezaquarii** [comment]
Ok, I get it that you don't want to work on it (especially that it's pretty feature complete). How about updating maven build? I guess you need to have proper credentials to do it.

**Comment by ezaquarii** [comment]
If you just want to get rid of the ballast, I'm happy to take it. I use this lib in few projects and I found it very useful.

**Comment by oxo42** [comment]
I have assigned you push privileges to the repo.  If you want to transfer it into it's own github org, I'd be happy for that as well.

**Comment by ezaquarii** [comment]
@oxo42 I'd like to transfer it to my github, thank you. :)

**Comment by ezaquarii** [comment]
I think I misunderstood the message. NVM. :)
